# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='标题'),
        ),
    ]
