# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_templates', '0003_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(default='', verbose_name='文章url链接'),
        ),
    ]
