# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_templates', '0005_verifycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_templates.News', verbose_name='新闻')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'news')]),
        ),
    ]
