# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_templates', '0006_auto_20181022_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='user_id',
            new_name='user',
        ),
    ]
