# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_templates', '0007_auto_20181022_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to='image/%Y/%m'),
        ),
    ]
