# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-29 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_templates', '0008_auto_20181024_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_templates.News', verbose_name='新闻id')),
            ],
            options={
                'verbose_name': '用户浏览记录',
                'verbose_name_plural': '用户浏览记录',
            },
        ),
        migrations.RemoveField(
            model_name='relation',
            name='news_id',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='img/default.png', upload_to='image/%Y/%m'),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.AddField(
            model_name='browserhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
    ]
